#!/usr/bin/env python
import sys
import os
import argparse
import GEOparse


def parse(args):

    description = """
    gsm2fastq v0.1
    """

    p = argparse.ArgumentParser(
        description=description
    )

    p.add_argument("term",
                   help="GEO accession",
                   metavar="GSM"
                   )
    p.add_argument("email",
                   help="e-mail address for Entrez API",
                   metavar="EMAIL"
                   )
    p.add_argument("-o", "--outdir",
                   dest="outdir",
                   help="output directory",
                   metavar="DIR",
                   default="./"
                   )
    p.add_argument("-f", "--filetype",
                   dest="filetype",
                   help="filetype (fastq or sra)",
                   metavar="TYPE",
                   default="fastq"
                   )

    return p.parse_args(args)

if __name__ == "__main__":
    args = parse(sys.argv[1:])
    #if not args.term.startswith("GSE"):
    #    raise NotImplementedError("only GSM ids work for now!")
    if args.term.startswith("GSE"):
        gse = GEOparse.get_GEO(args.term)
        gse.download_SRA(
            email=args.email, 
            directory=args.outdir,
            filetype=args.filetype,
            aspera="ASPERA_HOME" in os.environ,
        )
    #title = gsm.metadata.get("title", [])[0]
    else:
        downloader = GEOparse.sra_downloader.SRADownloader(
            args.term,
            args.email,
            directory=args.outdir,
            filetype=args.filetype,
            aspera="ASPERA_HOME" in os.environ,
            )
        downloader.download()
    #print("Supp_{}_{}".format(gsm.name, title))
